routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('customer','App\Http\Controllers\CustomerController');

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    protected $fillable=[
	'custname','comment','rating',

	];

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customer=Customer::latest()->paginate(5);
        return view('customer.index',compact('customer'))->with('i',(request()->input('page',1)-1)*5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'custname'=> 'required',
            'comment'=> 'required',
            'rating'=> 'required',
        ]);

        customer::create($request->all());
        return redirect()->route('customer.index')->with('success','customer comment logged.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        return view('customer.show',compact('customer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        return view('customer.edit',compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer)
    {
        $request->validate([

        ]);

        $customer->update($request->all());

        return redirect()->route('customer.index')->with('success','Customer comment updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        $customer->delete();

        return redirect()->route('customer.index')->with('Customer comment deleted');
    }
}

resources/views/customer/create.blade.php
@extends('customer.layout')

@section('content')

	<div class="row bg-dark text-white">

		<div class="col-lg-12 margin-tb">

			<div class="pull-left">

				<h2> New Comment</h2>
			</div>

			<div class="pull-right">

				<a class="btn btn-warning" href="{{route('customer.index')}}">Back</a>

			</div>

		</div>

		@if ($errors->any())

			<div class="alert alert-danger">

				<strong>UHHMMMM</strong> you messed up.<br><br>

				<ul>

					@foreach($errors->all() as$error)

					<li>{{$error}}</li>

					@endforeach

				</ul>

			</div>

		@endif

			<form action="{{route('customer.store')}}" method="POST">

				@csrf

				<div class="row">

					<div class="col-cs-12 col-sm-12 col-md-12">

						<div class="form-group">

							<strong>CustomerName:</strong>

								<input type="text" name="custname" class="form-control" placeholder="custname">

						</div>
					</div>

					<div class="col-cs-12 col-sm-12 col-md-12">

						<div class="form-group">

							<strong>Comment</strong>

							<input type="text" name="comment" class="form-control" placeholder="comment">

						</div>

					</div>

					<div class="col-xs-12 col-sm-12 col-md-12">

						<div class="form-group">

							<strong>Rating</strong>

							<input type="text" name="rating" class="form-control" placeholder="rating">

						</div>

					</div>

					<div class="col-xs-12 col-sm-12 col-md-12 text-center">

						<button type="submit" class="btn btn-warning">Submit</button>

					</div>
				</div>

			</form>

			@endsection

resources/views/customer/edit.blade.php
@extends('customer.layout')

@section('content')

	<div class="row">

		<div class="col-lg-12 margin-tb bg-dark text-white">

			<div class="pull-left">

				<h2>Edit Comment</h2>
			</div>

			<div class="pull-right">

				<a class="btn btn-warning" href="{{route('customer.index')}}">Back</a>

			</div>
		</div>

	</div>

	@if($errors->any())

		<div class="alert alert-danger">

			<strong>UHHHMMM!</strong>You messed up.<br><br>

			<ul>

				@foreach($errors->all() as $error)

				<li>{{$error}}</li>

				@endforeach
			</ul>

		</div>

	@endif


	<form action="{{route('customer.update',$customer->id)}}" method="POST" >

		@csrf

		@method('PUT')

		<div class="row bg-dark text-white">

			<div class="col-cs-12 col-sm-12 col-md-12">

				<div class="form-group">

					<strong>CustName:</strong>

					<input type="text" name="custname" value="{{$customer->custname}}" class="form-control" placeholder="Name">

				</div>
			</div>

			<div class="col-cs-12 col-sm-12 col-md-12">

				<div class="form-group">

					<strong>Comment</strong>

					<input type="text" name="comment" value="{{$customer->comment}}" class="form-control" placeholder="comment">

				</div>

			</div>

			<div class="col-cs-12 col-sm-12 col-md-12">

				<div class="form-group">

					<strong>Rating</strong>

					<input type="text" name="rating" value="{{$customer->rating}}" class="form-control" placeholder="rating">

				</div>

			</div>


			<div class="col-cs-12 col-sm-12 col-md-12 text-center">

				<button type="submit" class="btn btn-warning">Submit</button>

			</div>

		</div>

	</form>

	@endsection

resources/views/customer/index.blade.php
@extends('customer.layout')

@section('content')


<div class="pull-left bg-dark text-white p-2">

	<h2> Customer Comments Wall</h2>
</div>


<div class="row">
	<div class="col-lg-12 margin- bg-dark">

		<div class="pull-right">

         <a class="btn btn-warning" href="{{route('customer.create')}}"> New Comment</a>

		</div>
	</div>
</div>

	@if($message=Session::get('success'))

	<div class="alert alert-success">

		<p>{{$message}}</p>
	</div>

@endif

	<table class="table table-bordered bg-dark text-white">

		<tr>

			<th>Que</th>

			<th>Name</th>

			<th>Comment</th>

			<th>Rating</th>

			<th width="280px">Action</th>
		</tr>

@foreach ($customer as $customer)

	<tr>

		<td>{{++$i}}</td>

		<td>{{$customer->custname}}</td>
		<td>{{$customer->comment}}</td>
		<td>{{$customer->rating}}</td>

		<td>

			<form action="{{route('customer.destroy',$customer->id)}}" method="POST">

			
			<a class= "btn btn-success" href="{{route('customer.edit',$customer->id)}}">Edit
			</a>

	@csrf
	@method('DELETE')

				<button type="submit" class="btn btn-danger">Delete</button>

			</form>
		</td>

	</tr>

@endforeach
</table>

resources/views/customer/layout.blade.php
<!DOCTYPE HTML>

<html>

<head>

	<title>Customer comments Wall</title>

	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

</head>

<body>
	
	<div class="container">

		@yield('content')

	</div>


</body>

</html>